version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    expose:
      - 9200
      - 9300

  redis:
    image: 'redis:6.2.6'
    expose:
      - 6379

  etl:
    build:
      context: .
      dockerfile: etl/Dockerfile
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    depends_on:
      - etl
    ports:
      - "8000:8000"

volumes:
  esdata:
    driver: local
